services:
  web:
    build:
      context: .
      dockerfile: docker/dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./static/screenshots:/app/static/screenshots
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/web_scraper_db
      - PYTHONUNBUFFERED=1

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=web_scraper_db

volumes:
  mongodb_data: