"""add index

Revision ID: 82ac297a18b6
Revises: 881327fa6ba0
Create Date: 2025-09-07 22:45:29.897067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ac297a18b6'
down_revision = '881327fa6ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('book_url_idx'))
        batch_op.create_index('books_class_from_class_to_idx', ['class_from', 'class_to'], unique=False)
        batch_op.create_index('books_class_from_idx', ['class_from'], unique=False)
        batch_op.create_index('books_part_idx', ['part'], unique=False)
        batch_op.create_index('books_program_idx', ['program'], unique=False)
        batch_op.create_index('books_publisher_idx', ['publisher'], unique=False)
        batch_op.create_index('books_series_idx', ['series'], unique=False)
        batch_op.create_index('books_subject_idx', ['subject'], unique=False)
        batch_op.create_index('books_url_idx', ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('books_url_idx')
        batch_op.drop_index('books_subject_idx')
        batch_op.drop_index('books_series_idx')
        batch_op.drop_index('books_publisher_idx')
        batch_op.drop_index('books_program_idx')
        batch_op.drop_index('books_part_idx')
        batch_op.drop_index('books_class_from_idx')
        batch_op.drop_index('books_class_from_class_to_idx')
        batch_op.create_index(batch_op.f('book_url_idx'), ['url'], unique=False)

    # ### end Alembic commands ###
