"""Add indexes to books table

Revision ID: 881327fa6ba0
Revises: 
Create Date: 2025-09-07 22:15:07.532072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881327fa6ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('book_url_idx', ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('book_url_idx')

    # ### end Alembic commands ###
