"""delete index

Revision ID: cb453ae5230e
Revises: e972a5efa3df
Create Date: 2025-09-07 23:22:30.596296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb453ae5230e'
down_revision = 'e972a5efa3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('books_authors_idx'))
        batch_op.drop_index(batch_op.f('books_class_from_class_to_idx'))
        batch_op.drop_index(batch_op.f('books_class_from_idx'))
        batch_op.drop_index(batch_op.f('books_part_idx'))
        batch_op.drop_index(batch_op.f('books_program_idx'))
        batch_op.drop_index(batch_op.f('books_publisher_idx'))
        batch_op.drop_index(batch_op.f('books_series_idx'))
        batch_op.drop_index(batch_op.f('books_subject_idx'))
        batch_op.drop_index(batch_op.f('books_url_idx'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('books_url_idx'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('books_subject_idx'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('books_series_idx'), ['series'], unique=False)
        batch_op.create_index(batch_op.f('books_publisher_idx'), ['publisher'], unique=False)
        batch_op.create_index(batch_op.f('books_program_idx'), ['program'], unique=False)
        batch_op.create_index(batch_op.f('books_part_idx'), ['part'], unique=False)
        batch_op.create_index(batch_op.f('books_class_from_idx'), ['class_from'], unique=False)
        batch_op.create_index(batch_op.f('books_class_from_class_to_idx'), ['class_from', 'class_to'], unique=False)
        batch_op.create_index(batch_op.f('books_authors_idx'), ['authors'], unique=False)

    # ### end Alembic commands ###
